"""003_add_officials_lineups_discipline

Revision ID: 2f3a4e9e7cc2
Revises: 002
Create Date: 2026-03-10 11:12:21.366064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3a4e9e7cc2'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_officials_organization_id', 'officials', ['organization_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('disciplinary_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('division_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('suspension_matches', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disciplinary_match_id', 'disciplinary_actions', ['match_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_disciplinary_player_id', 'disciplinary_actions', ['player_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_disciplinary_season_id', 'disciplinary_actions', ['season_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('lineups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('starting', sa.Boolean(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='lineups_player_per_match_unique')
    )
    op.create_index('idx_lineups_match_id', 'lineups', ['match_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_lineups_team_id', 'lineups', ['team_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('match_officials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('official_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'official_id', name='match_officials_unique')
    )
    op.drop_index(op.f('idx_groups_division_id'), table_name='groups', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_matches_division_id'), table_name='matches', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('player_registrations_division_id_fkey'), 'player_registrations', type_='foreignkey')
    op.drop_column('player_registrations', 'division_id')
    op.drop_index(op.f('idx_teams_division_id'), table_name='teams', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_teams_division_id'), 'teams', ['division_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.add_column('player_registrations', sa.Column('division_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('player_registrations_division_id_fkey'), 'player_registrations', 'divisions', ['division_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_matches_division_id'), 'matches', ['division_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_groups_division_id'), 'groups', ['division_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_table('match_officials')
    op.drop_index('idx_lineups_team_id', table_name='lineups', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_lineups_match_id', table_name='lineups', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('lineups')
    op.drop_index('idx_disciplinary_season_id', table_name='disciplinary_actions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_disciplinary_player_id', table_name='disciplinary_actions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_disciplinary_match_id', table_name='disciplinary_actions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('disciplinary_actions')
    op.drop_index('idx_officials_organization_id', table_name='officials', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('officials')
    # ### end Alembic commands ###
